name: supagen
description: A CLI tool to automate manual effort/repetitive things when using Supabase.
version: 1.0.0
repository: https://github.com/supagen/supagen

environment:
  sdk: ^3.5.2

dependencies:
  args: ^2.4.2
  cli_completion: ^0.5.1
  dio: ^5.7.0
  get_it: ^7.7.0
  io: ^1.0.4
  mason: ^0.1.0-dev.60
  scope: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.12
  build_version: ^2.1.1
  lints: ^4.0.0
  test: ^1.24.0
